export const plan = [
  {
    day: 1,
    title: "Arrays, Strings Basics",
    problems: [
      "Reverse a String / Array",
      "Check Palindrome",
      "Find Maximum & Minimum in Array",
      "Count Frequency of Elements",
      "Anagram Check",
      "Remove Duplicates from Array",
    ],
  },
  {
    day: 2,
    title: "Array Manipulations & Number Patterns",
    problems: [
      "Sum of Digits",
      "Difference Between Odd & Even Index Elements",
      "Valid Parentheses",
      "Fibonacci Series",
      "Largest Number from Array",
      "Second Largest Element",
      "Count Vowels & Consonants",
    ],
  },
  {
    day: 3,
    title: "Array Operations & Searching",
    problems: [
      "Rotate Array by K",
      "Binary Search",
      "nCr Calculation",
      "Two Sum Problem",
      "Maximum Vacation Days",
      "Largest Number from Array (Repeat for confidence)",
    ],
  },
  {
    day: 4,
    title: "Greedy Foundations & Intervals",
    problems: [
      "Activity Selection",
      "Minimum Platforms",
      "Kadane's Algorithm",
      "Coin Change",
      "Sliding Window Problems (pick at least 2: Subarray Sum, Max/Min Window)",
      "Merge Overlapping Intervals",
    ],
  },
  {
    day: 5,
    title: "HashMap, Prefix, Bit Manipulation, Simple Recursion",
    problems: [
      "Count Divisible Subarrays",
      "Longest Common Prefix",
      "Sort Characters by Frequency",
      "Next Greater Element",
      "Binary String to Decimal",
      "Valid Parentheses (second approach/variation if time)",
    ],
  },
  {
    day: 6,
    title: "XOR & Bit, Subsets, Recursion Advanced",
    problems: [
      "XOR Single Number",
      "Maximum XOR of Two Numbers",
      "Subset Sum Check",
      "Count Arrays with Divisibility Condition",
      "Remove Digit to Maximize Number",
    ],
  },
  {
    day: 7,
    title: "Dynamic Programming Basics",
    problems: [
      "Longest Common Subsequence (LCS)",
      "0/1 Knapsack Problem",
      "Subset Sum (DP approach)",
      "Word Break Problem",
      "Combination Sum",
    ],
  },
  {
    day: 8,
    title: "DP Advanced, Hard Patterns",
    problems: [
      "LIS with Bitwise Condition",
      "Monster Defeat Problem",
      "Minimum Base with Identical Digits",
      "Minimum Days for Terrain Road",
      "Mountain Array Minimum Changes",
    ],
  },
  {
    day: 9,
    title: "Graphs, Backtracking, Hard/Edge Questions",
    problems: [
      "Dijkstra's Algorithm (Practice BFS/DFS for understanding)",
      "N-Queens (Classic Backtracking)",
      "Pack Gifts into K Boxes",
      "Wine Bottle Transport",
      "Max XOR-Sum(x)",
      "Maximum XOR Subset",
    ],
  },
  {
    day: 10,
    title: "Frequently Asked, Revision, Timed Practice",
    problems: [
      "Andy's Vacation",
      "Minimize Ugliness of Binary String",
      "Minimum Coins Required",
      "Recap problems you struggled with from previous days",
      "Simulate 3-hour mock (1 easy, 1 medium, 1 hard)",
      "Rapid revisit: starred/high-frequency repeat questions",
    ],
  },
];